# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cb7qwkp3n-capi-aws
  namespace: cb7qwkp3n
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cb7qwkp3n-capi-aws
subjects:
- kind: ServiceAccount
  name: cb7qwkp3n-capi-aws
